# Generated by Django 5.2.1 on 2025-05-23 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_username_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
