volumes:
  pg_data:
  static:


services:

  db:
    image: postgres:13.20
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./todolist/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file: .env
    depends_on:
      - db
    

