# Generated by Django 5.2.1 on 2025-05-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astanahubparticipant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='astanahubparticipant',
            name='description',
        ),
        migrations.RemoveField(
            model_name='astanahubparticipant',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='astanahubparticipant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='astanahubparticipant',
            name='website',
        ),
        migrations.AddField(
            model_name='astanahubparticipant',
            name='bin',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='astanahubparticipant',
            name='certificate_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='astanahubparticipant',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='astanahubparticipant',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='astanahubparticipant',
            name='issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='astanahubparticipant',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
